package gr.manousos.model;
// Generated Apr 16, 2013 12:57:37 AM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * E1dataFromTaxPayerFolder generated by hbm2java
 */
public class E1dataFromTaxPayerFolder  implements java.io.Serializable {


     private Integer idE1dataFromTaxPayerFolder;
     private Float 901;
     private Float 902;
     private Float 903;
     private Float 904;
     private Float 341;
     private Float 995;
     private Float 996;
     private Set<E1> e1s = new HashSet<E1>(0);

    public E1dataFromTaxPayerFolder() {
    }

    public E1dataFromTaxPayerFolder(Float 901, Float 902, Float 903, Float 904, Float 341, Float 995, Float 996, Set<E1> e1s) {
       this.901 = 901;
       this.902 = 902;
       this.903 = 903;
       this.904 = 904;
       this.341 = 341;
       this.995 = 995;
       this.996 = 996;
       this.e1s = e1s;
    }
   
    public Integer getIdE1dataFromTaxPayerFolder() {
        return this.idE1dataFromTaxPayerFolder;
    }
    
    public void setIdE1dataFromTaxPayerFolder(Integer idE1dataFromTaxPayerFolder) {
        this.idE1dataFromTaxPayerFolder = idE1dataFromTaxPayerFolder;
    }
    public Float get901() {
        return this.901;
    }
    
    public void set901(Float 901) {
        this.901 = 901;
    }
    public Float get902() {
        return this.902;
    }
    
    public void set902(Float 902) {
        this.902 = 902;
    }
    public Float get903() {
        return this.903;
    }
    
    public void set903(Float 903) {
        this.903 = 903;
    }
    public Float get904() {
        return this.904;
    }
    
    public void set904(Float 904) {
        this.904 = 904;
    }
    public Float get341() {
        return this.341;
    }
    
    public void set341(Float 341) {
        this.341 = 341;
    }
    public Float get995() {
        return this.995;
    }
    
    public void set995(Float 995) {
        this.995 = 995;
    }
    public Float get996() {
        return this.996;
    }
    
    public void set996(Float 996) {
        this.996 = 996;
    }
    public Set<E1> getE1s() {
        return this.e1s;
    }
    
    public void setE1s(Set<E1> e1s) {
        this.e1s = e1s;
    }




}


