package gr.manousos.model;
// Generated 3 Ιουν 2013 11:58:42 μμ by Hibernate Tools 3.4.0.CR1



/**
 * E1dataFromTaxPayerFolder generated by hbm2java
 */
public class E1dataFromTaxPayerFolder  implements java.io.Serializable {


     private E1dataFromTaxPayerFolderId id;
     private E1 e1;
     private Float 901;
     private Float 902;
     private Float 903;
     private Float 904;
     private Float 341;
     private Float 995;
     private Float 996;

    public E1dataFromTaxPayerFolder() {
    }

	
    public E1dataFromTaxPayerFolder(E1 e1) {
        this.e1 = e1;
    }
    public E1dataFromTaxPayerFolder(E1 e1, Float 901, Float 902, Float 903, Float 904, Float 341, Float 995, Float 996) {
       this.e1 = e1;
       this.901 = 901;
       this.902 = 902;
       this.903 = 903;
       this.904 = 904;
       this.341 = 341;
       this.995 = 995;
       this.996 = 996;
    }
   
    public E1dataFromTaxPayerFolderId getId() {
        return this.id;
    }
    
    public void setId(E1dataFromTaxPayerFolderId id) {
        this.id = id;
    }
    public E1 getE1() {
        return this.e1;
    }
    
    public void setE1(E1 e1) {
        this.e1 = e1;
    }
    public Float get901() {
        return this.901;
    }
    
    public void set901(Float 901) {
        this.901 = 901;
    }
    public Float get902() {
        return this.902;
    }
    
    public void set902(Float 902) {
        this.902 = 902;
    }
    public Float get903() {
        return this.903;
    }
    
    public void set903(Float 903) {
        this.903 = 903;
    }
    public Float get904() {
        return this.904;
    }
    
    public void set904(Float 904) {
        this.904 = 904;
    }
    public Float get341() {
        return this.341;
    }
    
    public void set341(Float 341) {
        this.341 = 341;
    }
    public Float get995() {
        return this.995;
    }
    
    public void set995(Float 995) {
        this.995 = 995;
    }
    public Float get996() {
        return this.996;
    }
    
    public void set996(Float 996) {
        this.996 = 996;
    }




}


