package gr.manousos.model;
// Generated 27 Φεβ 2013 12:29:40 πμ by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * E1dataFromTaxPayerFolder generated by hbm2java
 */
public class E1dataFromTaxPayerFolder  implements java.io.Serializable {


     private Integer idE1dataFromTaxPayerFolder;
     private Float 901;
     private Float 902;
     private Float 903;
     private Float 904;
     private Float 341;
     private Float 342;
     private Float 745;
     private Float 746;
     private Float 995;
     private Float 996;
     private Float 997;
     private Float 998;
     private Float 959;
     private Float 960;
     private Float 743;
     private Float 744;
     private Float 323;
     private Float 324;
     private Float 399;
     private Float 400;
     private Float 907;
     private Float 908;
     private Float 985;
     private Float 986;
     private Float 987;
     private Float 988;
     private Float 989;
     private Float 990;
     private Set<E1> e1s = new HashSet<E1>(0);

    public E1dataFromTaxPayerFolder() {
    }

    public E1dataFromTaxPayerFolder(Float 901, Float 902, Float 903, Float 904, Float 341, Float 342, Float 745, Float 746, Float 995, Float 996, Float 997, Float 998, Float 959, Float 960, Float 743, Float 744, Float 323, Float 324, Float 399, Float 400, Float 907, Float 908, Float 985, Float 986, Float 987, Float 988, Float 989, Float 990, Set<E1> e1s) {
       this.901 = 901;
       this.902 = 902;
       this.903 = 903;
       this.904 = 904;
       this.341 = 341;
       this.342 = 342;
       this.745 = 745;
       this.746 = 746;
       this.995 = 995;
       this.996 = 996;
       this.997 = 997;
       this.998 = 998;
       this.959 = 959;
       this.960 = 960;
       this.743 = 743;
       this.744 = 744;
       this.323 = 323;
       this.324 = 324;
       this.399 = 399;
       this.400 = 400;
       this.907 = 907;
       this.908 = 908;
       this.985 = 985;
       this.986 = 986;
       this.987 = 987;
       this.988 = 988;
       this.989 = 989;
       this.990 = 990;
       this.e1s = e1s;
    }
   
    public Integer getIdE1dataFromTaxPayerFolder() {
        return this.idE1dataFromTaxPayerFolder;
    }
    
    public void setIdE1dataFromTaxPayerFolder(Integer idE1dataFromTaxPayerFolder) {
        this.idE1dataFromTaxPayerFolder = idE1dataFromTaxPayerFolder;
    }
    public Float get901() {
        return this.901;
    }
    
    public void set901(Float 901) {
        this.901 = 901;
    }
    public Float get902() {
        return this.902;
    }
    
    public void set902(Float 902) {
        this.902 = 902;
    }
    public Float get903() {
        return this.903;
    }
    
    public void set903(Float 903) {
        this.903 = 903;
    }
    public Float get904() {
        return this.904;
    }
    
    public void set904(Float 904) {
        this.904 = 904;
    }
    public Float get341() {
        return this.341;
    }
    
    public void set341(Float 341) {
        this.341 = 341;
    }
    public Float get342() {
        return this.342;
    }
    
    public void set342(Float 342) {
        this.342 = 342;
    }
    public Float get745() {
        return this.745;
    }
    
    public void set745(Float 745) {
        this.745 = 745;
    }
    public Float get746() {
        return this.746;
    }
    
    public void set746(Float 746) {
        this.746 = 746;
    }
    public Float get995() {
        return this.995;
    }
    
    public void set995(Float 995) {
        this.995 = 995;
    }
    public Float get996() {
        return this.996;
    }
    
    public void set996(Float 996) {
        this.996 = 996;
    }
    public Float get997() {
        return this.997;
    }
    
    public void set997(Float 997) {
        this.997 = 997;
    }
    public Float get998() {
        return this.998;
    }
    
    public void set998(Float 998) {
        this.998 = 998;
    }
    public Float get959() {
        return this.959;
    }
    
    public void set959(Float 959) {
        this.959 = 959;
    }
    public Float get960() {
        return this.960;
    }
    
    public void set960(Float 960) {
        this.960 = 960;
    }
    public Float get743() {
        return this.743;
    }
    
    public void set743(Float 743) {
        this.743 = 743;
    }
    public Float get744() {
        return this.744;
    }
    
    public void set744(Float 744) {
        this.744 = 744;
    }
    public Float get323() {
        return this.323;
    }
    
    public void set323(Float 323) {
        this.323 = 323;
    }
    public Float get324() {
        return this.324;
    }
    
    public void set324(Float 324) {
        this.324 = 324;
    }
    public Float get399() {
        return this.399;
    }
    
    public void set399(Float 399) {
        this.399 = 399;
    }
    public Float get400() {
        return this.400;
    }
    
    public void set400(Float 400) {
        this.400 = 400;
    }
    public Float get907() {
        return this.907;
    }
    
    public void set907(Float 907) {
        this.907 = 907;
    }
    public Float get908() {
        return this.908;
    }
    
    public void set908(Float 908) {
        this.908 = 908;
    }
    public Float get985() {
        return this.985;
    }
    
    public void set985(Float 985) {
        this.985 = 985;
    }
    public Float get986() {
        return this.986;
    }
    
    public void set986(Float 986) {
        this.986 = 986;
    }
    public Float get987() {
        return this.987;
    }
    
    public void set987(Float 987) {
        this.987 = 987;
    }
    public Float get988() {
        return this.988;
    }
    
    public void set988(Float 988) {
        this.988 = 988;
    }
    public Float get989() {
        return this.989;
    }
    
    public void set989(Float 989) {
        this.989 = 989;
    }
    public Float get990() {
        return this.990;
    }
    
    public void set990(Float 990) {
        this.990 = 990;
    }
    public Set<E1> getE1s() {
        return this.e1s;
    }
    
    public void setE1s(Set<E1> e1s) {
        this.e1s = e1s;
    }




}


