package gr.manousos.model;
// Generated 3 Μαρ 2013 10:07:00 μμ by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * E1expensesRemovedFromTotalIncome generated by hbm2java
 */
public class E1expensesRemovedFromTotalIncome  implements java.io.Serializable {


     private Integer idE1expensesRemovedFromTotalIncome;
     private Float 049;
     private Float 051;
     private Float 052;
     private Float 053;
     private Float 054;
     private Float 057;
     private Float 058;
     private Float 031;
     private Float 032;
     private Float 059;
     private Float 060;
     private Float 075;
     private Float 076;
     private Float 061;
     private Float 062;
     private Float 071;
     private Float 063;
     private Float 064;
     private Float 069;
     private Float 070;
     private String rentalForFamilyOwnerName1;
     private String 801;
     private Integer 092;
     private Float 091;
     private Integer 097;
     private Float 811;
     private Float 812;
     private String rentalForFamilyOwnerName2;
     private String 802;
     private Integer 094;
     private Float 093;
     private Integer 098;
     private Float 813;
     private Float 814;
     private String rentalForFamilyOwnerName3;
     private String 803;
     private Integer 096;
     private Float 095;
     private Float 099;
     private Float 815;
     private Float 816;
     private String rentalForStudyOwnerName1;
     private String 804;
     private Float 817;
     private String rentalForStudyOwnerName2;
     private String 805;
     private Float 819;
     private String rentalForStudyOwnerName3;
     private String 806;
     private Float 821;
     private String rentalForStudyOwnerName4;
     private String 807;
     private Float 823;
     private Float 073;
     private Float 074;
     private Float 089;
     private Float 090;
     private Float 087;
     private Float 088;
     private Float 079;
     private Float 080;
     private Float 084;
     private Float 085;
     private Float 077;
     private Float 078;
     private Float 663;
     private Float 664;
     private Integer 033;
     private Integer 034;
     private Integer 035;
     private Integer 036;
     private Set<E1> e1s = new HashSet<E1>(0);

    public E1expensesRemovedFromTotalIncome() {
    }

    public E1expensesRemovedFromTotalIncome(Float 049, Float 051, Float 052, Float 053, Float 054, Float 057, Float 058, Float 031, Float 032, Float 059, Float 060, Float 075, Float 076, Float 061, Float 062, Float 071, Float 063, Float 064, Float 069, Float 070, String rentalForFamilyOwnerName1, String 801, Integer 092, Float 091, Integer 097, Float 811, Float 812, String rentalForFamilyOwnerName2, String 802, Integer 094, Float 093, Integer 098, Float 813, Float 814, String rentalForFamilyOwnerName3, String 803, Integer 096, Float 095, Float 099, Float 815, Float 816, String rentalForStudyOwnerName1, String 804, Float 817, String rentalForStudyOwnerName2, String 805, Float 819, String rentalForStudyOwnerName3, String 806, Float 821, String rentalForStudyOwnerName4, String 807, Float 823, Float 073, Float 074, Float 089, Float 090, Float 087, Float 088, Float 079, Float 080, Float 084, Float 085, Float 077, Float 078, Float 663, Float 664, Integer 033, Integer 034, Integer 035, Integer 036, Set<E1> e1s) {
       this.049 = 049;
       this.051 = 051;
       this.052 = 052;
       this.053 = 053;
       this.054 = 054;
       this.057 = 057;
       this.058 = 058;
       this.031 = 031;
       this.032 = 032;
       this.059 = 059;
       this.060 = 060;
       this.075 = 075;
       this.076 = 076;
       this.061 = 061;
       this.062 = 062;
       this.071 = 071;
       this.063 = 063;
       this.064 = 064;
       this.069 = 069;
       this.070 = 070;
       this.rentalForFamilyOwnerName1 = rentalForFamilyOwnerName1;
       this.801 = 801;
       this.092 = 092;
       this.091 = 091;
       this.097 = 097;
       this.811 = 811;
       this.812 = 812;
       this.rentalForFamilyOwnerName2 = rentalForFamilyOwnerName2;
       this.802 = 802;
       this.094 = 094;
       this.093 = 093;
       this.098 = 098;
       this.813 = 813;
       this.814 = 814;
       this.rentalForFamilyOwnerName3 = rentalForFamilyOwnerName3;
       this.803 = 803;
       this.096 = 096;
       this.095 = 095;
       this.099 = 099;
       this.815 = 815;
       this.816 = 816;
       this.rentalForStudyOwnerName1 = rentalForStudyOwnerName1;
       this.804 = 804;
       this.817 = 817;
       this.rentalForStudyOwnerName2 = rentalForStudyOwnerName2;
       this.805 = 805;
       this.819 = 819;
       this.rentalForStudyOwnerName3 = rentalForStudyOwnerName3;
       this.806 = 806;
       this.821 = 821;
       this.rentalForStudyOwnerName4 = rentalForStudyOwnerName4;
       this.807 = 807;
       this.823 = 823;
       this.073 = 073;
       this.074 = 074;
       this.089 = 089;
       this.090 = 090;
       this.087 = 087;
       this.088 = 088;
       this.079 = 079;
       this.080 = 080;
       this.084 = 084;
       this.085 = 085;
       this.077 = 077;
       this.078 = 078;
       this.663 = 663;
       this.664 = 664;
       this.033 = 033;
       this.034 = 034;
       this.035 = 035;
       this.036 = 036;
       this.e1s = e1s;
    }
   
    public Integer getIdE1expensesRemovedFromTotalIncome() {
        return this.idE1expensesRemovedFromTotalIncome;
    }
    
    public void setIdE1expensesRemovedFromTotalIncome(Integer idE1expensesRemovedFromTotalIncome) {
        this.idE1expensesRemovedFromTotalIncome = idE1expensesRemovedFromTotalIncome;
    }
    public Float get049() {
        return this.049;
    }
    
    public void set049(Float 049) {
        this.049 = 049;
    }
    public Float get051() {
        return this.051;
    }
    
    public void set051(Float 051) {
        this.051 = 051;
    }
    public Float get052() {
        return this.052;
    }
    
    public void set052(Float 052) {
        this.052 = 052;
    }
    public Float get053() {
        return this.053;
    }
    
    public void set053(Float 053) {
        this.053 = 053;
    }
    public Float get054() {
        return this.054;
    }
    
    public void set054(Float 054) {
        this.054 = 054;
    }
    public Float get057() {
        return this.057;
    }
    
    public void set057(Float 057) {
        this.057 = 057;
    }
    public Float get058() {
        return this.058;
    }
    
    public void set058(Float 058) {
        this.058 = 058;
    }
    public Float get031() {
        return this.031;
    }
    
    public void set031(Float 031) {
        this.031 = 031;
    }
    public Float get032() {
        return this.032;
    }
    
    public void set032(Float 032) {
        this.032 = 032;
    }
    public Float get059() {
        return this.059;
    }
    
    public void set059(Float 059) {
        this.059 = 059;
    }
    public Float get060() {
        return this.060;
    }
    
    public void set060(Float 060) {
        this.060 = 060;
    }
    public Float get075() {
        return this.075;
    }
    
    public void set075(Float 075) {
        this.075 = 075;
    }
    public Float get076() {
        return this.076;
    }
    
    public void set076(Float 076) {
        this.076 = 076;
    }
    public Float get061() {
        return this.061;
    }
    
    public void set061(Float 061) {
        this.061 = 061;
    }
    public Float get062() {
        return this.062;
    }
    
    public void set062(Float 062) {
        this.062 = 062;
    }
    public Float get071() {
        return this.071;
    }
    
    public void set071(Float 071) {
        this.071 = 071;
    }
    public Float get063() {
        return this.063;
    }
    
    public void set063(Float 063) {
        this.063 = 063;
    }
    public Float get064() {
        return this.064;
    }
    
    public void set064(Float 064) {
        this.064 = 064;
    }
    public Float get069() {
        return this.069;
    }
    
    public void set069(Float 069) {
        this.069 = 069;
    }
    public Float get070() {
        return this.070;
    }
    
    public void set070(Float 070) {
        this.070 = 070;
    }
    public String getRentalForFamilyOwnerName1() {
        return this.rentalForFamilyOwnerName1;
    }
    
    public void setRentalForFamilyOwnerName1(String rentalForFamilyOwnerName1) {
        this.rentalForFamilyOwnerName1 = rentalForFamilyOwnerName1;
    }
    public String get801() {
        return this.801;
    }
    
    public void set801(String 801) {
        this.801 = 801;
    }
    public Integer get092() {
        return this.092;
    }
    
    public void set092(Integer 092) {
        this.092 = 092;
    }
    public Float get091() {
        return this.091;
    }
    
    public void set091(Float 091) {
        this.091 = 091;
    }
    public Integer get097() {
        return this.097;
    }
    
    public void set097(Integer 097) {
        this.097 = 097;
    }
    public Float get811() {
        return this.811;
    }
    
    public void set811(Float 811) {
        this.811 = 811;
    }
    public Float get812() {
        return this.812;
    }
    
    public void set812(Float 812) {
        this.812 = 812;
    }
    public String getRentalForFamilyOwnerName2() {
        return this.rentalForFamilyOwnerName2;
    }
    
    public void setRentalForFamilyOwnerName2(String rentalForFamilyOwnerName2) {
        this.rentalForFamilyOwnerName2 = rentalForFamilyOwnerName2;
    }
    public String get802() {
        return this.802;
    }
    
    public void set802(String 802) {
        this.802 = 802;
    }
    public Integer get094() {
        return this.094;
    }
    
    public void set094(Integer 094) {
        this.094 = 094;
    }
    public Float get093() {
        return this.093;
    }
    
    public void set093(Float 093) {
        this.093 = 093;
    }
    public Integer get098() {
        return this.098;
    }
    
    public void set098(Integer 098) {
        this.098 = 098;
    }
    public Float get813() {
        return this.813;
    }
    
    public void set813(Float 813) {
        this.813 = 813;
    }
    public Float get814() {
        return this.814;
    }
    
    public void set814(Float 814) {
        this.814 = 814;
    }
    public String getRentalForFamilyOwnerName3() {
        return this.rentalForFamilyOwnerName3;
    }
    
    public void setRentalForFamilyOwnerName3(String rentalForFamilyOwnerName3) {
        this.rentalForFamilyOwnerName3 = rentalForFamilyOwnerName3;
    }
    public String get803() {
        return this.803;
    }
    
    public void set803(String 803) {
        this.803 = 803;
    }
    public Integer get096() {
        return this.096;
    }
    
    public void set096(Integer 096) {
        this.096 = 096;
    }
    public Float get095() {
        return this.095;
    }
    
    public void set095(Float 095) {
        this.095 = 095;
    }
    public Float get099() {
        return this.099;
    }
    
    public void set099(Float 099) {
        this.099 = 099;
    }
    public Float get815() {
        return this.815;
    }
    
    public void set815(Float 815) {
        this.815 = 815;
    }
    public Float get816() {
        return this.816;
    }
    
    public void set816(Float 816) {
        this.816 = 816;
    }
    public String getRentalForStudyOwnerName1() {
        return this.rentalForStudyOwnerName1;
    }
    
    public void setRentalForStudyOwnerName1(String rentalForStudyOwnerName1) {
        this.rentalForStudyOwnerName1 = rentalForStudyOwnerName1;
    }
    public String get804() {
        return this.804;
    }
    
    public void set804(String 804) {
        this.804 = 804;
    }
    public Float get817() {
        return this.817;
    }
    
    public void set817(Float 817) {
        this.817 = 817;
    }
    public String getRentalForStudyOwnerName2() {
        return this.rentalForStudyOwnerName2;
    }
    
    public void setRentalForStudyOwnerName2(String rentalForStudyOwnerName2) {
        this.rentalForStudyOwnerName2 = rentalForStudyOwnerName2;
    }
    public String get805() {
        return this.805;
    }
    
    public void set805(String 805) {
        this.805 = 805;
    }
    public Float get819() {
        return this.819;
    }
    
    public void set819(Float 819) {
        this.819 = 819;
    }
    public String getRentalForStudyOwnerName3() {
        return this.rentalForStudyOwnerName3;
    }
    
    public void setRentalForStudyOwnerName3(String rentalForStudyOwnerName3) {
        this.rentalForStudyOwnerName3 = rentalForStudyOwnerName3;
    }
    public String get806() {
        return this.806;
    }
    
    public void set806(String 806) {
        this.806 = 806;
    }
    public Float get821() {
        return this.821;
    }
    
    public void set821(Float 821) {
        this.821 = 821;
    }
    public String getRentalForStudyOwnerName4() {
        return this.rentalForStudyOwnerName4;
    }
    
    public void setRentalForStudyOwnerName4(String rentalForStudyOwnerName4) {
        this.rentalForStudyOwnerName4 = rentalForStudyOwnerName4;
    }
    public String get807() {
        return this.807;
    }
    
    public void set807(String 807) {
        this.807 = 807;
    }
    public Float get823() {
        return this.823;
    }
    
    public void set823(Float 823) {
        this.823 = 823;
    }
    public Float get073() {
        return this.073;
    }
    
    public void set073(Float 073) {
        this.073 = 073;
    }
    public Float get074() {
        return this.074;
    }
    
    public void set074(Float 074) {
        this.074 = 074;
    }
    public Float get089() {
        return this.089;
    }
    
    public void set089(Float 089) {
        this.089 = 089;
    }
    public Float get090() {
        return this.090;
    }
    
    public void set090(Float 090) {
        this.090 = 090;
    }
    public Float get087() {
        return this.087;
    }
    
    public void set087(Float 087) {
        this.087 = 087;
    }
    public Float get088() {
        return this.088;
    }
    
    public void set088(Float 088) {
        this.088 = 088;
    }
    public Float get079() {
        return this.079;
    }
    
    public void set079(Float 079) {
        this.079 = 079;
    }
    public Float get080() {
        return this.080;
    }
    
    public void set080(Float 080) {
        this.080 = 080;
    }
    public Float get084() {
        return this.084;
    }
    
    public void set084(Float 084) {
        this.084 = 084;
    }
    public Float get085() {
        return this.085;
    }
    
    public void set085(Float 085) {
        this.085 = 085;
    }
    public Float get077() {
        return this.077;
    }
    
    public void set077(Float 077) {
        this.077 = 077;
    }
    public Float get078() {
        return this.078;
    }
    
    public void set078(Float 078) {
        this.078 = 078;
    }
    public Float get663() {
        return this.663;
    }
    
    public void set663(Float 663) {
        this.663 = 663;
    }
    public Float get664() {
        return this.664;
    }
    
    public void set664(Float 664) {
        this.664 = 664;
    }
    public Integer get033() {
        return this.033;
    }
    
    public void set033(Integer 033) {
        this.033 = 033;
    }
    public Integer get034() {
        return this.034;
    }
    
    public void set034(Integer 034) {
        this.034 = 034;
    }
    public Integer get035() {
        return this.035;
    }
    
    public void set035(Integer 035) {
        this.035 = 035;
    }
    public Integer get036() {
        return this.036;
    }
    
    public void set036(Integer 036) {
        this.036 = 036;
    }
    public Set<E1> getE1s() {
        return this.e1s;
    }
    
    public void setE1s(Set<E1> e1s) {
        this.e1s = e1s;
    }




}


