package gr.manousos.model;
// Generated 3 Ιουν 2013 11:58:42 μμ by Hibernate Tools 3.4.0.CR1



/**
 * E1incomesReduceTaxes generated by hbm2java
 */
public class E1incomesReduceTaxes  implements java.io.Serializable {


     private E1incomesReduceTaxesId id;
     private E1 e1;
     private Float 655;
     private Float 656;
     private Float 693;
     private Float 694;
     private Float 659;
     private Float 660;
     private Float 657;
     private Float 658;
     private Float 661;
     private Float 662;
     private Float 431;
     private Float 432;
     private Float 433;
     private Float 434;
     private Float 305;
     private Float 306;
     private Float 477;
     private Float 478;
     private String lessorName1;
     private String 790;
     private Float 795;
     private String lassorName2;
     private String 791;
     private Float 796;
     private Float 793;
     private Float 794;
     private Float 615;
     private Float 616;
     private String lassorNameForStudent;
     private String 417;
     private Float areaStudentHouse;
     private Float 419;
     private Float 420;
     private Float 735;
     private Float 736;
     private Float 781;
     private Float 782;
     private Float 783;
     private Float 784;
     private Float 787;
     private Float 788;

    public E1incomesReduceTaxes() {
    }

	
    public E1incomesReduceTaxes(E1 e1) {
        this.e1 = e1;
    }
    public E1incomesReduceTaxes(E1 e1, Float 655, Float 656, Float 693, Float 694, Float 659, Float 660, Float 657, Float 658, Float 661, Float 662, Float 431, Float 432, Float 433, Float 434, Float 305, Float 306, Float 477, Float 478, String lessorName1, String 790, Float 795, String lassorName2, String 791, Float 796, Float 793, Float 794, Float 615, Float 616, String lassorNameForStudent, String 417, Float areaStudentHouse, Float 419, Float 420, Float 735, Float 736, Float 781, Float 782, Float 783, Float 784, Float 787, Float 788) {
       this.e1 = e1;
       this.655 = 655;
       this.656 = 656;
       this.693 = 693;
       this.694 = 694;
       this.659 = 659;
       this.660 = 660;
       this.657 = 657;
       this.658 = 658;
       this.661 = 661;
       this.662 = 662;
       this.431 = 431;
       this.432 = 432;
       this.433 = 433;
       this.434 = 434;
       this.305 = 305;
       this.306 = 306;
       this.477 = 477;
       this.478 = 478;
       this.lessorName1 = lessorName1;
       this.790 = 790;
       this.795 = 795;
       this.lassorName2 = lassorName2;
       this.791 = 791;
       this.796 = 796;
       this.793 = 793;
       this.794 = 794;
       this.615 = 615;
       this.616 = 616;
       this.lassorNameForStudent = lassorNameForStudent;
       this.417 = 417;
       this.areaStudentHouse = areaStudentHouse;
       this.419 = 419;
       this.420 = 420;
       this.735 = 735;
       this.736 = 736;
       this.781 = 781;
       this.782 = 782;
       this.783 = 783;
       this.784 = 784;
       this.787 = 787;
       this.788 = 788;
    }
   
    public E1incomesReduceTaxesId getId() {
        return this.id;
    }
    
    public void setId(E1incomesReduceTaxesId id) {
        this.id = id;
    }
    public E1 getE1() {
        return this.e1;
    }
    
    public void setE1(E1 e1) {
        this.e1 = e1;
    }
    public Float get655() {
        return this.655;
    }
    
    public void set655(Float 655) {
        this.655 = 655;
    }
    public Float get656() {
        return this.656;
    }
    
    public void set656(Float 656) {
        this.656 = 656;
    }
    public Float get693() {
        return this.693;
    }
    
    public void set693(Float 693) {
        this.693 = 693;
    }
    public Float get694() {
        return this.694;
    }
    
    public void set694(Float 694) {
        this.694 = 694;
    }
    public Float get659() {
        return this.659;
    }
    
    public void set659(Float 659) {
        this.659 = 659;
    }
    public Float get660() {
        return this.660;
    }
    
    public void set660(Float 660) {
        this.660 = 660;
    }
    public Float get657() {
        return this.657;
    }
    
    public void set657(Float 657) {
        this.657 = 657;
    }
    public Float get658() {
        return this.658;
    }
    
    public void set658(Float 658) {
        this.658 = 658;
    }
    public Float get661() {
        return this.661;
    }
    
    public void set661(Float 661) {
        this.661 = 661;
    }
    public Float get662() {
        return this.662;
    }
    
    public void set662(Float 662) {
        this.662 = 662;
    }
    public Float get431() {
        return this.431;
    }
    
    public void set431(Float 431) {
        this.431 = 431;
    }
    public Float get432() {
        return this.432;
    }
    
    public void set432(Float 432) {
        this.432 = 432;
    }
    public Float get433() {
        return this.433;
    }
    
    public void set433(Float 433) {
        this.433 = 433;
    }
    public Float get434() {
        return this.434;
    }
    
    public void set434(Float 434) {
        this.434 = 434;
    }
    public Float get305() {
        return this.305;
    }
    
    public void set305(Float 305) {
        this.305 = 305;
    }
    public Float get306() {
        return this.306;
    }
    
    public void set306(Float 306) {
        this.306 = 306;
    }
    public Float get477() {
        return this.477;
    }
    
    public void set477(Float 477) {
        this.477 = 477;
    }
    public Float get478() {
        return this.478;
    }
    
    public void set478(Float 478) {
        this.478 = 478;
    }
    public String getLessorName1() {
        return this.lessorName1;
    }
    
    public void setLessorName1(String lessorName1) {
        this.lessorName1 = lessorName1;
    }
    public String get790() {
        return this.790;
    }
    
    public void set790(String 790) {
        this.790 = 790;
    }
    public Float get795() {
        return this.795;
    }
    
    public void set795(Float 795) {
        this.795 = 795;
    }
    public String getLassorName2() {
        return this.lassorName2;
    }
    
    public void setLassorName2(String lassorName2) {
        this.lassorName2 = lassorName2;
    }
    public String get791() {
        return this.791;
    }
    
    public void set791(String 791) {
        this.791 = 791;
    }
    public Float get796() {
        return this.796;
    }
    
    public void set796(Float 796) {
        this.796 = 796;
    }
    public Float get793() {
        return this.793;
    }
    
    public void set793(Float 793) {
        this.793 = 793;
    }
    public Float get794() {
        return this.794;
    }
    
    public void set794(Float 794) {
        this.794 = 794;
    }
    public Float get615() {
        return this.615;
    }
    
    public void set615(Float 615) {
        this.615 = 615;
    }
    public Float get616() {
        return this.616;
    }
    
    public void set616(Float 616) {
        this.616 = 616;
    }
    public String getLassorNameForStudent() {
        return this.lassorNameForStudent;
    }
    
    public void setLassorNameForStudent(String lassorNameForStudent) {
        this.lassorNameForStudent = lassorNameForStudent;
    }
    public String get417() {
        return this.417;
    }
    
    public void set417(String 417) {
        this.417 = 417;
    }
    public Float getAreaStudentHouse() {
        return this.areaStudentHouse;
    }
    
    public void setAreaStudentHouse(Float areaStudentHouse) {
        this.areaStudentHouse = areaStudentHouse;
    }
    public Float get419() {
        return this.419;
    }
    
    public void set419(Float 419) {
        this.419 = 419;
    }
    public Float get420() {
        return this.420;
    }
    
    public void set420(Float 420) {
        this.420 = 420;
    }
    public Float get735() {
        return this.735;
    }
    
    public void set735(Float 735) {
        this.735 = 735;
    }
    public Float get736() {
        return this.736;
    }
    
    public void set736(Float 736) {
        this.736 = 736;
    }
    public Float get781() {
        return this.781;
    }
    
    public void set781(Float 781) {
        this.781 = 781;
    }
    public Float get782() {
        return this.782;
    }
    
    public void set782(Float 782) {
        this.782 = 782;
    }
    public Float get783() {
        return this.783;
    }
    
    public void set783(Float 783) {
        this.783 = 783;
    }
    public Float get784() {
        return this.784;
    }
    
    public void set784(Float 784) {
        this.784 = 784;
    }
    public Float get787() {
        return this.787;
    }
    
    public void set787(Float 787) {
        this.787 = 787;
    }
    public Float get788() {
        return this.788;
    }
    
    public void set788(Float 788) {
        this.788 = 788;
    }




}


