package gr.manousos.model;
// Generated 18 Μαρ 2013 12:42:56 πμ by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * E1infoData generated by hbm2java
 */
public class E1infoData  implements java.io.Serializable {


     private Integer e1infoDataId;
     private Integer 327;
     private Integer 328;
     private Integer 319;
     private Integer 320;
     private Integer 023;
     private Integer 024;
     private Integer 329;
     private Integer 330;
     private Integer 331;
     private Integer 011;
     private Integer 012;
     private Integer 013;
     private Integer 014;
     private Integer 015;
     private Integer 016;
     private Integer 017;
     private Integer 018;
     private Integer 021;
     private Integer 022;
     private Integer 025;
     private Integer 026;
     private Integer 007;
     private Integer 008;
     private Integer 617;
     private Integer 385;
     private Integer 386;
     private Integer 029;
     private Integer 030;
     private Integer 905;
     private Integer 906;
     private Integer 911;
     private Integer 912;
     private Integer 010;
     private Set<E1> e1s = new HashSet<E1>(0);

    public E1infoData() {
    }

    public E1infoData(Integer 327, Integer 328, Integer 319, Integer 320, Integer 023, Integer 024, Integer 329, Integer 330, Integer 331, Integer 011, Integer 012, Integer 013, Integer 014, Integer 015, Integer 016, Integer 017, Integer 018, Integer 021, Integer 022, Integer 025, Integer 026, Integer 007, Integer 008, Integer 617, Integer 385, Integer 386, Integer 029, Integer 030, Integer 905, Integer 906, Integer 911, Integer 912, Integer 010, Set<E1> e1s) {
       this.327 = 327;
       this.328 = 328;
       this.319 = 319;
       this.320 = 320;
       this.023 = 023;
       this.024 = 024;
       this.329 = 329;
       this.330 = 330;
       this.331 = 331;
       this.011 = 011;
       this.012 = 012;
       this.013 = 013;
       this.014 = 014;
       this.015 = 015;
       this.016 = 016;
       this.017 = 017;
       this.018 = 018;
       this.021 = 021;
       this.022 = 022;
       this.025 = 025;
       this.026 = 026;
       this.007 = 007;
       this.008 = 008;
       this.617 = 617;
       this.385 = 385;
       this.386 = 386;
       this.029 = 029;
       this.030 = 030;
       this.905 = 905;
       this.906 = 906;
       this.911 = 911;
       this.912 = 912;
       this.010 = 010;
       this.e1s = e1s;
    }
   
    public Integer getE1infoDataId() {
        return this.e1infoDataId;
    }
    
    public void setE1infoDataId(Integer e1infoDataId) {
        this.e1infoDataId = e1infoDataId;
    }
    public Integer get327() {
        return this.327;
    }
    
    public void set327(Integer 327) {
        this.327 = 327;
    }
    public Integer get328() {
        return this.328;
    }
    
    public void set328(Integer 328) {
        this.328 = 328;
    }
    public Integer get319() {
        return this.319;
    }
    
    public void set319(Integer 319) {
        this.319 = 319;
    }
    public Integer get320() {
        return this.320;
    }
    
    public void set320(Integer 320) {
        this.320 = 320;
    }
    public Integer get023() {
        return this.023;
    }
    
    public void set023(Integer 023) {
        this.023 = 023;
    }
    public Integer get024() {
        return this.024;
    }
    
    public void set024(Integer 024) {
        this.024 = 024;
    }
    public Integer get329() {
        return this.329;
    }
    
    public void set329(Integer 329) {
        this.329 = 329;
    }
    public Integer get330() {
        return this.330;
    }
    
    public void set330(Integer 330) {
        this.330 = 330;
    }
    public Integer get331() {
        return this.331;
    }
    
    public void set331(Integer 331) {
        this.331 = 331;
    }
    public Integer get011() {
        return this.011;
    }
    
    public void set011(Integer 011) {
        this.011 = 011;
    }
    public Integer get012() {
        return this.012;
    }
    
    public void set012(Integer 012) {
        this.012 = 012;
    }
    public Integer get013() {
        return this.013;
    }
    
    public void set013(Integer 013) {
        this.013 = 013;
    }
    public Integer get014() {
        return this.014;
    }
    
    public void set014(Integer 014) {
        this.014 = 014;
    }
    public Integer get015() {
        return this.015;
    }
    
    public void set015(Integer 015) {
        this.015 = 015;
    }
    public Integer get016() {
        return this.016;
    }
    
    public void set016(Integer 016) {
        this.016 = 016;
    }
    public Integer get017() {
        return this.017;
    }
    
    public void set017(Integer 017) {
        this.017 = 017;
    }
    public Integer get018() {
        return this.018;
    }
    
    public void set018(Integer 018) {
        this.018 = 018;
    }
    public Integer get021() {
        return this.021;
    }
    
    public void set021(Integer 021) {
        this.021 = 021;
    }
    public Integer get022() {
        return this.022;
    }
    
    public void set022(Integer 022) {
        this.022 = 022;
    }
    public Integer get025() {
        return this.025;
    }
    
    public void set025(Integer 025) {
        this.025 = 025;
    }
    public Integer get026() {
        return this.026;
    }
    
    public void set026(Integer 026) {
        this.026 = 026;
    }
    public Integer get007() {
        return this.007;
    }
    
    public void set007(Integer 007) {
        this.007 = 007;
    }
    public Integer get008() {
        return this.008;
    }
    
    public void set008(Integer 008) {
        this.008 = 008;
    }
    public Integer get617() {
        return this.617;
    }
    
    public void set617(Integer 617) {
        this.617 = 617;
    }
    public Integer get385() {
        return this.385;
    }
    
    public void set385(Integer 385) {
        this.385 = 385;
    }
    public Integer get386() {
        return this.386;
    }
    
    public void set386(Integer 386) {
        this.386 = 386;
    }
    public Integer get029() {
        return this.029;
    }
    
    public void set029(Integer 029) {
        this.029 = 029;
    }
    public Integer get030() {
        return this.030;
    }
    
    public void set030(Integer 030) {
        this.030 = 030;
    }
    public Integer get905() {
        return this.905;
    }
    
    public void set905(Integer 905) {
        this.905 = 905;
    }
    public Integer get906() {
        return this.906;
    }
    
    public void set906(Integer 906) {
        this.906 = 906;
    }
    public Integer get911() {
        return this.911;
    }
    
    public void set911(Integer 911) {
        this.911 = 911;
    }
    public Integer get912() {
        return this.912;
    }
    
    public void set912(Integer 912) {
        this.912 = 912;
    }
    public Integer get010() {
        return this.010;
    }
    
    public void set010(Integer 010) {
        this.010 = 010;
    }
    public Set<E1> getE1s() {
        return this.e1s;
    }
    
    public void setE1s(Set<E1> e1s) {
        this.e1s = e1s;
    }




}


