package gr.manousos.model;
// Generated Apr 16, 2013 12:57:37 AM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * E1nauticalincomes generated by hbm2java
 */
public class E1nauticalincomes  implements java.io.Serializable {


     private Integer idE1nauticalincomes;
     private Float 255;
     private Float 256;
     private Float 257;
     private Float 258;
     private Float 263;
     private Float 264;
     private Float 265;
     private Float 266;
     private Float 253;
     private Float 254;
     private Float 201;
     private Float 202;
     private Set<E1> e1s = new HashSet<E1>(0);

    public E1nauticalincomes() {
    }

    public E1nauticalincomes(Float 255, Float 256, Float 257, Float 258, Float 263, Float 264, Float 265, Float 266, Float 253, Float 254, Float 201, Float 202, Set<E1> e1s) {
       this.255 = 255;
       this.256 = 256;
       this.257 = 257;
       this.258 = 258;
       this.263 = 263;
       this.264 = 264;
       this.265 = 265;
       this.266 = 266;
       this.253 = 253;
       this.254 = 254;
       this.201 = 201;
       this.202 = 202;
       this.e1s = e1s;
    }
   
    public Integer getIdE1nauticalincomes() {
        return this.idE1nauticalincomes;
    }
    
    public void setIdE1nauticalincomes(Integer idE1nauticalincomes) {
        this.idE1nauticalincomes = idE1nauticalincomes;
    }
    public Float get255() {
        return this.255;
    }
    
    public void set255(Float 255) {
        this.255 = 255;
    }
    public Float get256() {
        return this.256;
    }
    
    public void set256(Float 256) {
        this.256 = 256;
    }
    public Float get257() {
        return this.257;
    }
    
    public void set257(Float 257) {
        this.257 = 257;
    }
    public Float get258() {
        return this.258;
    }
    
    public void set258(Float 258) {
        this.258 = 258;
    }
    public Float get263() {
        return this.263;
    }
    
    public void set263(Float 263) {
        this.263 = 263;
    }
    public Float get264() {
        return this.264;
    }
    
    public void set264(Float 264) {
        this.264 = 264;
    }
    public Float get265() {
        return this.265;
    }
    
    public void set265(Float 265) {
        this.265 = 265;
    }
    public Float get266() {
        return this.266;
    }
    
    public void set266(Float 266) {
        this.266 = 266;
    }
    public Float get253() {
        return this.253;
    }
    
    public void set253(Float 253) {
        this.253 = 253;
    }
    public Float get254() {
        return this.254;
    }
    
    public void set254(Float 254) {
        this.254 = 254;
    }
    public Float get201() {
        return this.201;
    }
    
    public void set201(Float 201) {
        this.201 = 201;
    }
    public Float get202() {
        return this.202;
    }
    
    public void set202(Float 202) {
        this.202 = 202;
    }
    public Set<E1> getE1s() {
        return this.e1s;
    }
    
    public void setE1s(Set<E1> e1s) {
        this.e1s = e1s;
    }




}


