package gr.manousos.model;
// Generated 20 Μαρ 2013 11:40:46 μμ by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * E1objectiveSpending generated by hbm2java
 */
public class E1objectiveSpending  implements java.io.Serializable {


     private Integer idE1objectiveSpending;
     private String 205;
     private String houseAddr1;
     private String floor1;
     private Integer 203;
     private Integer 240;
     private Float 211;
     private Float 212;
     private Float 213;
     private Float 214;
     private Integer 215;
     private Float 216;
     private String houseAddr2;
     private String floor2;
     private Integer 207;
     private Integer 241;
     private Float 218;
     private Float 219;
     private Float 220;
     private Float 221;
     private Integer 222;
     private Float 223;
     private String houseAddr3;
     private String floor3;
     private Integer 209;
     private Integer 242;
     private Float 225;
     private Float 226;
     private Float 227;
     private Float 228;
     private Integer 229;
     private Float 230;
     private Float 707;
     private Float 708;
     private String afm1;
     private String 750;
     private Integer 703;
     private Integer 761;
     private Float 771;
     private Integer 775;
     private String afm2;
     private String 751;
     private Integer 704;
     private Integer 762;
     private Float 772;
     private Integer 776;
     private String afm3;
     private String 752;
     private Integer 705;
     private Integer 763;
     private Float 773;
     private Integer 777;
     private String afm4;
     private String 753;
     private Integer 706;
     private Integer 764;
     private Float 774;
     private Integer 778;
     private Float 851;
     private Float 852;
     private Float 853;
     private Float 854;
     private Float 855;
     private Float 856;
     private Float 857;
     private Float 858;
     private String shippingName1;
     private String shippingRegister1;
     private String shippingCountry1;
     private Integer sailShip1;
     private Integer accommodationSpace1;
     private Float percentPrincipalCoOwner1;
     private Float percentWifeCoOwner1;
     private Integer firstRegister1;
     private Integer ownershipMonths1;
     private Float 747;
     private String shippingName2;
     private String shippingRegister2;
     private String shippingCountry2;
     private Integer sailShip2;
     private Integer accommodationSpace2;
     private Float percentPrincipalCoOwner2;
     private Float percentWifeCoOwner2;
     private Integer firstRegister2;
     private Integer ownershipMonths2;
     private Float 748;
     private Float 711;
     private Float 712;
     private Float 713;
     private Float 714;
     private Float 731;
     private Float 732;
     private String aircraftRegisterData;
     private String aircraftType;
     private String aircraftSn;
     private String airportBase;
     private Integer aircraftOwnerShip;
     private Integer aircraftPowerLibres;
     private Integer aircraftFirstRegister;
     private Float 715;
     private Float 716;
     private Float 767;
     private Float poolPrincipalCoOwnerOutdoor;
     private Float poolWifeCoOwnerOutdoor;
     private Float 768;
     private Float poolPrincipalCoOwnerIndoor;
     private Float poolWifeCoOwnerIndoor;
     private Float 765;
     private Float 766;
     private Float 769;
     private Float 770;
     private Float 719;
     private Float 720;
     private Float 721;
     private Float 722;
     private Float 723;
     private Float 724;
     private Float 725;
     private Float 726;
     private Float 727;
     private Float 728;
     private Set<E1> e1s = new HashSet<E1>(0);

    public E1objectiveSpending() {
    }

    public E1objectiveSpending(String 205, String houseAddr1, String floor1, Integer 203, Integer 240, Float 211, Float 212, Float 213, Float 214, Integer 215, Float 216, String houseAddr2, String floor2, Integer 207, Integer 241, Float 218, Float 219, Float 220, Float 221, Integer 222, Float 223, String houseAddr3, String floor3, Integer 209, Integer 242, Float 225, Float 226, Float 227, Float 228, Integer 229, Float 230, Float 707, Float 708, String afm1, String 750, Integer 703, Integer 761, Float 771, Integer 775, String afm2, String 751, Integer 704, Integer 762, Float 772, Integer 776, String afm3, String 752, Integer 705, Integer 763, Float 773, Integer 777, String afm4, String 753, Integer 706, Integer 764, Float 774, Integer 778, Float 851, Float 852, Float 853, Float 854, Float 855, Float 856, Float 857, Float 858, String shippingName1, String shippingRegister1, String shippingCountry1, Integer sailShip1, Integer accommodationSpace1, Float percentPrincipalCoOwner1, Float percentWifeCoOwner1, Integer firstRegister1, Integer ownershipMonths1, Float 747, String shippingName2, String shippingRegister2, String shippingCountry2, Integer sailShip2, Integer accommodationSpace2, Float percentPrincipalCoOwner2, Float percentWifeCoOwner2, Integer firstRegister2, Integer ownershipMonths2, Float 748, Float 711, Float 712, Float 713, Float 714, Float 731, Float 732, String aircraftRegisterData, String aircraftType, String aircraftSn, String airportBase, Integer aircraftOwnerShip, Integer aircraftPowerLibres, Integer aircraftFirstRegister, Float 715, Float 716, Float 767, Float poolPrincipalCoOwnerOutdoor, Float poolWifeCoOwnerOutdoor, Float 768, Float poolPrincipalCoOwnerIndoor, Float poolWifeCoOwnerIndoor, Float 765, Float 766, Float 769, Float 770, Float 719, Float 720, Float 721, Float 722, Float 723, Float 724, Float 725, Float 726, Float 727, Float 728, Set<E1> e1s) {
       this.205 = 205;
       this.houseAddr1 = houseAddr1;
       this.floor1 = floor1;
       this.203 = 203;
       this.240 = 240;
       this.211 = 211;
       this.212 = 212;
       this.213 = 213;
       this.214 = 214;
       this.215 = 215;
       this.216 = 216;
       this.houseAddr2 = houseAddr2;
       this.floor2 = floor2;
       this.207 = 207;
       this.241 = 241;
       this.218 = 218;
       this.219 = 219;
       this.220 = 220;
       this.221 = 221;
       this.222 = 222;
       this.223 = 223;
       this.houseAddr3 = houseAddr3;
       this.floor3 = floor3;
       this.209 = 209;
       this.242 = 242;
       this.225 = 225;
       this.226 = 226;
       this.227 = 227;
       this.228 = 228;
       this.229 = 229;
       this.230 = 230;
       this.707 = 707;
       this.708 = 708;
       this.afm1 = afm1;
       this.750 = 750;
       this.703 = 703;
       this.761 = 761;
       this.771 = 771;
       this.775 = 775;
       this.afm2 = afm2;
       this.751 = 751;
       this.704 = 704;
       this.762 = 762;
       this.772 = 772;
       this.776 = 776;
       this.afm3 = afm3;
       this.752 = 752;
       this.705 = 705;
       this.763 = 763;
       this.773 = 773;
       this.777 = 777;
       this.afm4 = afm4;
       this.753 = 753;
       this.706 = 706;
       this.764 = 764;
       this.774 = 774;
       this.778 = 778;
       this.851 = 851;
       this.852 = 852;
       this.853 = 853;
       this.854 = 854;
       this.855 = 855;
       this.856 = 856;
       this.857 = 857;
       this.858 = 858;
       this.shippingName1 = shippingName1;
       this.shippingRegister1 = shippingRegister1;
       this.shippingCountry1 = shippingCountry1;
       this.sailShip1 = sailShip1;
       this.accommodationSpace1 = accommodationSpace1;
       this.percentPrincipalCoOwner1 = percentPrincipalCoOwner1;
       this.percentWifeCoOwner1 = percentWifeCoOwner1;
       this.firstRegister1 = firstRegister1;
       this.ownershipMonths1 = ownershipMonths1;
       this.747 = 747;
       this.shippingName2 = shippingName2;
       this.shippingRegister2 = shippingRegister2;
       this.shippingCountry2 = shippingCountry2;
       this.sailShip2 = sailShip2;
       this.accommodationSpace2 = accommodationSpace2;
       this.percentPrincipalCoOwner2 = percentPrincipalCoOwner2;
       this.percentWifeCoOwner2 = percentWifeCoOwner2;
       this.firstRegister2 = firstRegister2;
       this.ownershipMonths2 = ownershipMonths2;
       this.748 = 748;
       this.711 = 711;
       this.712 = 712;
       this.713 = 713;
       this.714 = 714;
       this.731 = 731;
       this.732 = 732;
       this.aircraftRegisterData = aircraftRegisterData;
       this.aircraftType = aircraftType;
       this.aircraftSn = aircraftSn;
       this.airportBase = airportBase;
       this.aircraftOwnerShip = aircraftOwnerShip;
       this.aircraftPowerLibres = aircraftPowerLibres;
       this.aircraftFirstRegister = aircraftFirstRegister;
       this.715 = 715;
       this.716 = 716;
       this.767 = 767;
       this.poolPrincipalCoOwnerOutdoor = poolPrincipalCoOwnerOutdoor;
       this.poolWifeCoOwnerOutdoor = poolWifeCoOwnerOutdoor;
       this.768 = 768;
       this.poolPrincipalCoOwnerIndoor = poolPrincipalCoOwnerIndoor;
       this.poolWifeCoOwnerIndoor = poolWifeCoOwnerIndoor;
       this.765 = 765;
       this.766 = 766;
       this.769 = 769;
       this.770 = 770;
       this.719 = 719;
       this.720 = 720;
       this.721 = 721;
       this.722 = 722;
       this.723 = 723;
       this.724 = 724;
       this.725 = 725;
       this.726 = 726;
       this.727 = 727;
       this.728 = 728;
       this.e1s = e1s;
    }
   
    public Integer getIdE1objectiveSpending() {
        return this.idE1objectiveSpending;
    }
    
    public void setIdE1objectiveSpending(Integer idE1objectiveSpending) {
        this.idE1objectiveSpending = idE1objectiveSpending;
    }
    public String get205() {
        return this.205;
    }
    
    public void set205(String 205) {
        this.205 = 205;
    }
    public String getHouseAddr1() {
        return this.houseAddr1;
    }
    
    public void setHouseAddr1(String houseAddr1) {
        this.houseAddr1 = houseAddr1;
    }
    public String getFloor1() {
        return this.floor1;
    }
    
    public void setFloor1(String floor1) {
        this.floor1 = floor1;
    }
    public Integer get203() {
        return this.203;
    }
    
    public void set203(Integer 203) {
        this.203 = 203;
    }
    public Integer get240() {
        return this.240;
    }
    
    public void set240(Integer 240) {
        this.240 = 240;
    }
    public Float get211() {
        return this.211;
    }
    
    public void set211(Float 211) {
        this.211 = 211;
    }
    public Float get212() {
        return this.212;
    }
    
    public void set212(Float 212) {
        this.212 = 212;
    }
    public Float get213() {
        return this.213;
    }
    
    public void set213(Float 213) {
        this.213 = 213;
    }
    public Float get214() {
        return this.214;
    }
    
    public void set214(Float 214) {
        this.214 = 214;
    }
    public Integer get215() {
        return this.215;
    }
    
    public void set215(Integer 215) {
        this.215 = 215;
    }
    public Float get216() {
        return this.216;
    }
    
    public void set216(Float 216) {
        this.216 = 216;
    }
    public String getHouseAddr2() {
        return this.houseAddr2;
    }
    
    public void setHouseAddr2(String houseAddr2) {
        this.houseAddr2 = houseAddr2;
    }
    public String getFloor2() {
        return this.floor2;
    }
    
    public void setFloor2(String floor2) {
        this.floor2 = floor2;
    }
    public Integer get207() {
        return this.207;
    }
    
    public void set207(Integer 207) {
        this.207 = 207;
    }
    public Integer get241() {
        return this.241;
    }
    
    public void set241(Integer 241) {
        this.241 = 241;
    }
    public Float get218() {
        return this.218;
    }
    
    public void set218(Float 218) {
        this.218 = 218;
    }
    public Float get219() {
        return this.219;
    }
    
    public void set219(Float 219) {
        this.219 = 219;
    }
    public Float get220() {
        return this.220;
    }
    
    public void set220(Float 220) {
        this.220 = 220;
    }
    public Float get221() {
        return this.221;
    }
    
    public void set221(Float 221) {
        this.221 = 221;
    }
    public Integer get222() {
        return this.222;
    }
    
    public void set222(Integer 222) {
        this.222 = 222;
    }
    public Float get223() {
        return this.223;
    }
    
    public void set223(Float 223) {
        this.223 = 223;
    }
    public String getHouseAddr3() {
        return this.houseAddr3;
    }
    
    public void setHouseAddr3(String houseAddr3) {
        this.houseAddr3 = houseAddr3;
    }
    public String getFloor3() {
        return this.floor3;
    }
    
    public void setFloor3(String floor3) {
        this.floor3 = floor3;
    }
    public Integer get209() {
        return this.209;
    }
    
    public void set209(Integer 209) {
        this.209 = 209;
    }
    public Integer get242() {
        return this.242;
    }
    
    public void set242(Integer 242) {
        this.242 = 242;
    }
    public Float get225() {
        return this.225;
    }
    
    public void set225(Float 225) {
        this.225 = 225;
    }
    public Float get226() {
        return this.226;
    }
    
    public void set226(Float 226) {
        this.226 = 226;
    }
    public Float get227() {
        return this.227;
    }
    
    public void set227(Float 227) {
        this.227 = 227;
    }
    public Float get228() {
        return this.228;
    }
    
    public void set228(Float 228) {
        this.228 = 228;
    }
    public Integer get229() {
        return this.229;
    }
    
    public void set229(Integer 229) {
        this.229 = 229;
    }
    public Float get230() {
        return this.230;
    }
    
    public void set230(Float 230) {
        this.230 = 230;
    }
    public Float get707() {
        return this.707;
    }
    
    public void set707(Float 707) {
        this.707 = 707;
    }
    public Float get708() {
        return this.708;
    }
    
    public void set708(Float 708) {
        this.708 = 708;
    }
    public String getAfm1() {
        return this.afm1;
    }
    
    public void setAfm1(String afm1) {
        this.afm1 = afm1;
    }
    public String get750() {
        return this.750;
    }
    
    public void set750(String 750) {
        this.750 = 750;
    }
    public Integer get703() {
        return this.703;
    }
    
    public void set703(Integer 703) {
        this.703 = 703;
    }
    public Integer get761() {
        return this.761;
    }
    
    public void set761(Integer 761) {
        this.761 = 761;
    }
    public Float get771() {
        return this.771;
    }
    
    public void set771(Float 771) {
        this.771 = 771;
    }
    public Integer get775() {
        return this.775;
    }
    
    public void set775(Integer 775) {
        this.775 = 775;
    }
    public String getAfm2() {
        return this.afm2;
    }
    
    public void setAfm2(String afm2) {
        this.afm2 = afm2;
    }
    public String get751() {
        return this.751;
    }
    
    public void set751(String 751) {
        this.751 = 751;
    }
    public Integer get704() {
        return this.704;
    }
    
    public void set704(Integer 704) {
        this.704 = 704;
    }
    public Integer get762() {
        return this.762;
    }
    
    public void set762(Integer 762) {
        this.762 = 762;
    }
    public Float get772() {
        return this.772;
    }
    
    public void set772(Float 772) {
        this.772 = 772;
    }
    public Integer get776() {
        return this.776;
    }
    
    public void set776(Integer 776) {
        this.776 = 776;
    }
    public String getAfm3() {
        return this.afm3;
    }
    
    public void setAfm3(String afm3) {
        this.afm3 = afm3;
    }
    public String get752() {
        return this.752;
    }
    
    public void set752(String 752) {
        this.752 = 752;
    }
    public Integer get705() {
        return this.705;
    }
    
    public void set705(Integer 705) {
        this.705 = 705;
    }
    public Integer get763() {
        return this.763;
    }
    
    public void set763(Integer 763) {
        this.763 = 763;
    }
    public Float get773() {
        return this.773;
    }
    
    public void set773(Float 773) {
        this.773 = 773;
    }
    public Integer get777() {
        return this.777;
    }
    
    public void set777(Integer 777) {
        this.777 = 777;
    }
    public String getAfm4() {
        return this.afm4;
    }
    
    public void setAfm4(String afm4) {
        this.afm4 = afm4;
    }
    public String get753() {
        return this.753;
    }
    
    public void set753(String 753) {
        this.753 = 753;
    }
    public Integer get706() {
        return this.706;
    }
    
    public void set706(Integer 706) {
        this.706 = 706;
    }
    public Integer get764() {
        return this.764;
    }
    
    public void set764(Integer 764) {
        this.764 = 764;
    }
    public Float get774() {
        return this.774;
    }
    
    public void set774(Float 774) {
        this.774 = 774;
    }
    public Integer get778() {
        return this.778;
    }
    
    public void set778(Integer 778) {
        this.778 = 778;
    }
    public Float get851() {
        return this.851;
    }
    
    public void set851(Float 851) {
        this.851 = 851;
    }
    public Float get852() {
        return this.852;
    }
    
    public void set852(Float 852) {
        this.852 = 852;
    }
    public Float get853() {
        return this.853;
    }
    
    public void set853(Float 853) {
        this.853 = 853;
    }
    public Float get854() {
        return this.854;
    }
    
    public void set854(Float 854) {
        this.854 = 854;
    }
    public Float get855() {
        return this.855;
    }
    
    public void set855(Float 855) {
        this.855 = 855;
    }
    public Float get856() {
        return this.856;
    }
    
    public void set856(Float 856) {
        this.856 = 856;
    }
    public Float get857() {
        return this.857;
    }
    
    public void set857(Float 857) {
        this.857 = 857;
    }
    public Float get858() {
        return this.858;
    }
    
    public void set858(Float 858) {
        this.858 = 858;
    }
    public String getShippingName1() {
        return this.shippingName1;
    }
    
    public void setShippingName1(String shippingName1) {
        this.shippingName1 = shippingName1;
    }
    public String getShippingRegister1() {
        return this.shippingRegister1;
    }
    
    public void setShippingRegister1(String shippingRegister1) {
        this.shippingRegister1 = shippingRegister1;
    }
    public String getShippingCountry1() {
        return this.shippingCountry1;
    }
    
    public void setShippingCountry1(String shippingCountry1) {
        this.shippingCountry1 = shippingCountry1;
    }
    public Integer getSailShip1() {
        return this.sailShip1;
    }
    
    public void setSailShip1(Integer sailShip1) {
        this.sailShip1 = sailShip1;
    }
    public Integer getAccommodationSpace1() {
        return this.accommodationSpace1;
    }
    
    public void setAccommodationSpace1(Integer accommodationSpace1) {
        this.accommodationSpace1 = accommodationSpace1;
    }
    public Float getPercentPrincipalCoOwner1() {
        return this.percentPrincipalCoOwner1;
    }
    
    public void setPercentPrincipalCoOwner1(Float percentPrincipalCoOwner1) {
        this.percentPrincipalCoOwner1 = percentPrincipalCoOwner1;
    }
    public Float getPercentWifeCoOwner1() {
        return this.percentWifeCoOwner1;
    }
    
    public void setPercentWifeCoOwner1(Float percentWifeCoOwner1) {
        this.percentWifeCoOwner1 = percentWifeCoOwner1;
    }
    public Integer getFirstRegister1() {
        return this.firstRegister1;
    }
    
    public void setFirstRegister1(Integer firstRegister1) {
        this.firstRegister1 = firstRegister1;
    }
    public Integer getOwnershipMonths1() {
        return this.ownershipMonths1;
    }
    
    public void setOwnershipMonths1(Integer ownershipMonths1) {
        this.ownershipMonths1 = ownershipMonths1;
    }
    public Float get747() {
        return this.747;
    }
    
    public void set747(Float 747) {
        this.747 = 747;
    }
    public String getShippingName2() {
        return this.shippingName2;
    }
    
    public void setShippingName2(String shippingName2) {
        this.shippingName2 = shippingName2;
    }
    public String getShippingRegister2() {
        return this.shippingRegister2;
    }
    
    public void setShippingRegister2(String shippingRegister2) {
        this.shippingRegister2 = shippingRegister2;
    }
    public String getShippingCountry2() {
        return this.shippingCountry2;
    }
    
    public void setShippingCountry2(String shippingCountry2) {
        this.shippingCountry2 = shippingCountry2;
    }
    public Integer getSailShip2() {
        return this.sailShip2;
    }
    
    public void setSailShip2(Integer sailShip2) {
        this.sailShip2 = sailShip2;
    }
    public Integer getAccommodationSpace2() {
        return this.accommodationSpace2;
    }
    
    public void setAccommodationSpace2(Integer accommodationSpace2) {
        this.accommodationSpace2 = accommodationSpace2;
    }
    public Float getPercentPrincipalCoOwner2() {
        return this.percentPrincipalCoOwner2;
    }
    
    public void setPercentPrincipalCoOwner2(Float percentPrincipalCoOwner2) {
        this.percentPrincipalCoOwner2 = percentPrincipalCoOwner2;
    }
    public Float getPercentWifeCoOwner2() {
        return this.percentWifeCoOwner2;
    }
    
    public void setPercentWifeCoOwner2(Float percentWifeCoOwner2) {
        this.percentWifeCoOwner2 = percentWifeCoOwner2;
    }
    public Integer getFirstRegister2() {
        return this.firstRegister2;
    }
    
    public void setFirstRegister2(Integer firstRegister2) {
        this.firstRegister2 = firstRegister2;
    }
    public Integer getOwnershipMonths2() {
        return this.ownershipMonths2;
    }
    
    public void setOwnershipMonths2(Integer ownershipMonths2) {
        this.ownershipMonths2 = ownershipMonths2;
    }
    public Float get748() {
        return this.748;
    }
    
    public void set748(Float 748) {
        this.748 = 748;
    }
    public Float get711() {
        return this.711;
    }
    
    public void set711(Float 711) {
        this.711 = 711;
    }
    public Float get712() {
        return this.712;
    }
    
    public void set712(Float 712) {
        this.712 = 712;
    }
    public Float get713() {
        return this.713;
    }
    
    public void set713(Float 713) {
        this.713 = 713;
    }
    public Float get714() {
        return this.714;
    }
    
    public void set714(Float 714) {
        this.714 = 714;
    }
    public Float get731() {
        return this.731;
    }
    
    public void set731(Float 731) {
        this.731 = 731;
    }
    public Float get732() {
        return this.732;
    }
    
    public void set732(Float 732) {
        this.732 = 732;
    }
    public String getAircraftRegisterData() {
        return this.aircraftRegisterData;
    }
    
    public void setAircraftRegisterData(String aircraftRegisterData) {
        this.aircraftRegisterData = aircraftRegisterData;
    }
    public String getAircraftType() {
        return this.aircraftType;
    }
    
    public void setAircraftType(String aircraftType) {
        this.aircraftType = aircraftType;
    }
    public String getAircraftSn() {
        return this.aircraftSn;
    }
    
    public void setAircraftSn(String aircraftSn) {
        this.aircraftSn = aircraftSn;
    }
    public String getAirportBase() {
        return this.airportBase;
    }
    
    public void setAirportBase(String airportBase) {
        this.airportBase = airportBase;
    }
    public Integer getAircraftOwnerShip() {
        return this.aircraftOwnerShip;
    }
    
    public void setAircraftOwnerShip(Integer aircraftOwnerShip) {
        this.aircraftOwnerShip = aircraftOwnerShip;
    }
    public Integer getAircraftPowerLibres() {
        return this.aircraftPowerLibres;
    }
    
    public void setAircraftPowerLibres(Integer aircraftPowerLibres) {
        this.aircraftPowerLibres = aircraftPowerLibres;
    }
    public Integer getAircraftFirstRegister() {
        return this.aircraftFirstRegister;
    }
    
    public void setAircraftFirstRegister(Integer aircraftFirstRegister) {
        this.aircraftFirstRegister = aircraftFirstRegister;
    }
    public Float get715() {
        return this.715;
    }
    
    public void set715(Float 715) {
        this.715 = 715;
    }
    public Float get716() {
        return this.716;
    }
    
    public void set716(Float 716) {
        this.716 = 716;
    }
    public Float get767() {
        return this.767;
    }
    
    public void set767(Float 767) {
        this.767 = 767;
    }
    public Float getPoolPrincipalCoOwnerOutdoor() {
        return this.poolPrincipalCoOwnerOutdoor;
    }
    
    public void setPoolPrincipalCoOwnerOutdoor(Float poolPrincipalCoOwnerOutdoor) {
        this.poolPrincipalCoOwnerOutdoor = poolPrincipalCoOwnerOutdoor;
    }
    public Float getPoolWifeCoOwnerOutdoor() {
        return this.poolWifeCoOwnerOutdoor;
    }
    
    public void setPoolWifeCoOwnerOutdoor(Float poolWifeCoOwnerOutdoor) {
        this.poolWifeCoOwnerOutdoor = poolWifeCoOwnerOutdoor;
    }
    public Float get768() {
        return this.768;
    }
    
    public void set768(Float 768) {
        this.768 = 768;
    }
    public Float getPoolPrincipalCoOwnerIndoor() {
        return this.poolPrincipalCoOwnerIndoor;
    }
    
    public void setPoolPrincipalCoOwnerIndoor(Float poolPrincipalCoOwnerIndoor) {
        this.poolPrincipalCoOwnerIndoor = poolPrincipalCoOwnerIndoor;
    }
    public Float getPoolWifeCoOwnerIndoor() {
        return this.poolWifeCoOwnerIndoor;
    }
    
    public void setPoolWifeCoOwnerIndoor(Float poolWifeCoOwnerIndoor) {
        this.poolWifeCoOwnerIndoor = poolWifeCoOwnerIndoor;
    }
    public Float get765() {
        return this.765;
    }
    
    public void set765(Float 765) {
        this.765 = 765;
    }
    public Float get766() {
        return this.766;
    }
    
    public void set766(Float 766) {
        this.766 = 766;
    }
    public Float get769() {
        return this.769;
    }
    
    public void set769(Float 769) {
        this.769 = 769;
    }
    public Float get770() {
        return this.770;
    }
    
    public void set770(Float 770) {
        this.770 = 770;
    }
    public Float get719() {
        return this.719;
    }
    
    public void set719(Float 719) {
        this.719 = 719;
    }
    public Float get720() {
        return this.720;
    }
    
    public void set720(Float 720) {
        this.720 = 720;
    }
    public Float get721() {
        return this.721;
    }
    
    public void set721(Float 721) {
        this.721 = 721;
    }
    public Float get722() {
        return this.722;
    }
    
    public void set722(Float 722) {
        this.722 = 722;
    }
    public Float get723() {
        return this.723;
    }
    
    public void set723(Float 723) {
        this.723 = 723;
    }
    public Float get724() {
        return this.724;
    }
    
    public void set724(Float 724) {
        this.724 = 724;
    }
    public Float get725() {
        return this.725;
    }
    
    public void set725(Float 725) {
        this.725 = 725;
    }
    public Float get726() {
        return this.726;
    }
    
    public void set726(Float 726) {
        this.726 = 726;
    }
    public Float get727() {
        return this.727;
    }
    
    public void set727(Float 727) {
        this.727 = 727;
    }
    public Float get728() {
        return this.728;
    }
    
    public void set728(Float 728) {
        this.728 = 728;
    }
    public Set<E1> getE1s() {
        return this.e1s;
    }
    
    public void setE1s(Set<E1> e1s) {
        this.e1s = e1s;
    }




}


