package gr.manousos.model;
// Generated 24 Απρ 2013 9:47:18 μμ by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * E1prepaidTaxes generated by hbm2java
 */
public class E1prepaidTaxes  implements java.io.Serializable {


     private Integer idE1prepaidTaxes;
     private Float 601;
     private Float 602;
     private Float 603;
     private Float 604;
     private Float 605;
     private Float 606;
     private Float 607;
     private Float 608;
     private Float 609;
     private Float 610;
     private Float 651;
     private Float 652;
     private Float 293;
     private Float 294;
     private Float 313;
     private Float 314;
     private Float 315;
     private Float 316;
     private Float 297;
     private Float 298;
     private Float 127;
     private Float 128;
     private Set<E1> e1s = new HashSet<E1>(0);

    public E1prepaidTaxes() {
    }

    public E1prepaidTaxes(Float 601, Float 602, Float 603, Float 604, Float 605, Float 606, Float 607, Float 608, Float 609, Float 610, Float 651, Float 652, Float 293, Float 294, Float 313, Float 314, Float 315, Float 316, Float 297, Float 298, Float 127, Float 128, Set<E1> e1s) {
       this.601 = 601;
       this.602 = 602;
       this.603 = 603;
       this.604 = 604;
       this.605 = 605;
       this.606 = 606;
       this.607 = 607;
       this.608 = 608;
       this.609 = 609;
       this.610 = 610;
       this.651 = 651;
       this.652 = 652;
       this.293 = 293;
       this.294 = 294;
       this.313 = 313;
       this.314 = 314;
       this.315 = 315;
       this.316 = 316;
       this.297 = 297;
       this.298 = 298;
       this.127 = 127;
       this.128 = 128;
       this.e1s = e1s;
    }
   
    public Integer getIdE1prepaidTaxes() {
        return this.idE1prepaidTaxes;
    }
    
    public void setIdE1prepaidTaxes(Integer idE1prepaidTaxes) {
        this.idE1prepaidTaxes = idE1prepaidTaxes;
    }
    public Float get601() {
        return this.601;
    }
    
    public void set601(Float 601) {
        this.601 = 601;
    }
    public Float get602() {
        return this.602;
    }
    
    public void set602(Float 602) {
        this.602 = 602;
    }
    public Float get603() {
        return this.603;
    }
    
    public void set603(Float 603) {
        this.603 = 603;
    }
    public Float get604() {
        return this.604;
    }
    
    public void set604(Float 604) {
        this.604 = 604;
    }
    public Float get605() {
        return this.605;
    }
    
    public void set605(Float 605) {
        this.605 = 605;
    }
    public Float get606() {
        return this.606;
    }
    
    public void set606(Float 606) {
        this.606 = 606;
    }
    public Float get607() {
        return this.607;
    }
    
    public void set607(Float 607) {
        this.607 = 607;
    }
    public Float get608() {
        return this.608;
    }
    
    public void set608(Float 608) {
        this.608 = 608;
    }
    public Float get609() {
        return this.609;
    }
    
    public void set609(Float 609) {
        this.609 = 609;
    }
    public Float get610() {
        return this.610;
    }
    
    public void set610(Float 610) {
        this.610 = 610;
    }
    public Float get651() {
        return this.651;
    }
    
    public void set651(Float 651) {
        this.651 = 651;
    }
    public Float get652() {
        return this.652;
    }
    
    public void set652(Float 652) {
        this.652 = 652;
    }
    public Float get293() {
        return this.293;
    }
    
    public void set293(Float 293) {
        this.293 = 293;
    }
    public Float get294() {
        return this.294;
    }
    
    public void set294(Float 294) {
        this.294 = 294;
    }
    public Float get313() {
        return this.313;
    }
    
    public void set313(Float 313) {
        this.313 = 313;
    }
    public Float get314() {
        return this.314;
    }
    
    public void set314(Float 314) {
        this.314 = 314;
    }
    public Float get315() {
        return this.315;
    }
    
    public void set315(Float 315) {
        this.315 = 315;
    }
    public Float get316() {
        return this.316;
    }
    
    public void set316(Float 316) {
        this.316 = 316;
    }
    public Float get297() {
        return this.297;
    }
    
    public void set297(Float 297) {
        this.297 = 297;
    }
    public Float get298() {
        return this.298;
    }
    
    public void set298(Float 298) {
        this.298 = 298;
    }
    public Float get127() {
        return this.127;
    }
    
    public void set127(Float 127) {
        this.127 = 127;
    }
    public Float get128() {
        return this.128;
    }
    
    public void set128(Float 128) {
        this.128 = 128;
    }
    public Set<E1> getE1s() {
        return this.e1s;
    }
    
    public void setE1s(Set<E1> e1s) {
        this.e1s = e1s;
    }




}


