package gr.manousos.model;
// Generated 3 Ιουν 2013 11:58:42 μμ by Hibernate Tools 3.4.0.CR1



/**
 * E1reduceTax generated by hbm2java
 */
public class E1reduceTax  implements java.io.Serializable {


     private E1reduceTaxId id;
     private E1 e1;
     private Integer 001;
     private Integer 002;
     private Integer 003;
     private Integer 004;
     private Integer 005;
     private Integer 006;

    public E1reduceTax() {
    }

	
    public E1reduceTax(E1 e1) {
        this.e1 = e1;
    }
    public E1reduceTax(E1 e1, Integer 001, Integer 002, Integer 003, Integer 004, Integer 005, Integer 006) {
       this.e1 = e1;
       this.001 = 001;
       this.002 = 002;
       this.003 = 003;
       this.004 = 004;
       this.005 = 005;
       this.006 = 006;
    }
   
    public E1reduceTaxId getId() {
        return this.id;
    }
    
    public void setId(E1reduceTaxId id) {
        this.id = id;
    }
    public E1 getE1() {
        return this.e1;
    }
    
    public void setE1(E1 e1) {
        this.e1 = e1;
    }
    public Integer get001() {
        return this.001;
    }
    
    public void set001(Integer 001) {
        this.001 = 001;
    }
    public Integer get002() {
        return this.002;
    }
    
    public void set002(Integer 002) {
        this.002 = 002;
    }
    public Integer get003() {
        return this.003;
    }
    
    public void set003(Integer 003) {
        this.003 = 003;
    }
    public Integer get004() {
        return this.004;
    }
    
    public void set004(Integer 004) {
        this.004 = 004;
    }
    public Integer get005() {
        return this.005;
    }
    
    public void set005(Integer 005) {
        this.005 = 005;
    }
    public Integer get006() {
        return this.006;
    }
    
    public void set006(Integer 006) {
        this.006 = 006;
    }




}


