package gr.manousos.model;

// Generated 8 Ιουν 2013 9:45:48 μμ by Hibernate Tools 3.4.0.CR1

/**
 * IncomeTaxId generated by hbm2java
 */
public class IncomeTaxId implements java.io.Serializable {

    private int taxpayerId;
    private int year;

    public IncomeTaxId() {
    }

    public IncomeTaxId(int taxpayerId, int year) {
	this.taxpayerId = taxpayerId;
	this.year = year;
    }

    public int getTaxpayerId() {
	return this.taxpayerId;
    }

    public void setTaxpayerId(int taxpayerId) {
	this.taxpayerId = taxpayerId;
    }

    public int getYear() {
	return this.year;
    }

    public void setYear(int year) {
	this.year = year;
    }

    public boolean equals(Object other) {
	if ((this == other))
	    return true;
	if ((other == null))
	    return false;
	if (!(other instanceof IncomeTaxId))
	    return false;
	IncomeTaxId castOther = (IncomeTaxId) other;

	return (this.getTaxpayerId() == castOther.getTaxpayerId())
		&& (this.getYear() == castOther.getYear());
    }

    public int hashCode() {
	int result = 17;

	result = 37 * result + this.getTaxpayerId();
	result = 37 * result + this.getYear();
	return result;
    }

}
