
package gr.manousos.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.0
 * Sat Jan 26 00:36:00 EET 2013
 * Generated source version: 2.7.0
 */

@XmlRootElement(name = "finalSubmitE2", namespace = "http://service.manousos.gr/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "finalSubmitE2", namespace = "http://service.manousos.gr/")

public class FinalSubmitE2 {

    @XmlElement(name = "arg0")
    private gr.manousos.model.E2 arg0;

    public gr.manousos.model.E2 getArg0() {
        return this.arg0;
    }

    public void setArg0(gr.manousos.model.E2 newArg0)  {
        this.arg0 = newArg0;
    }

}

