
package gr.manousos.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.0
 * Sun Jan 13 19:41:57 EET 2013
 * Generated source version: 2.7.0
 */

@XmlRootElement(name = "getE2DocByIdResponse", namespace = "http://service.manousos.gr/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getE2DocByIdResponse", namespace = "http://service.manousos.gr/")

public class GetE2DocByIdResponse {

    @XmlElement(name = "return")
    private gr.manousos.model.E2 _return;

    public gr.manousos.model.E2 getReturn() {
        return this._return;
    }

    public void setReturn(gr.manousos.model.E2 new_return)  {
        this._return = new_return;
    }

}

