
package gr.manousos.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.0
 * Sat Jan 26 00:35:23 EET 2013
 * Generated source version: 2.7.0
 */

@XmlRootElement(name = "getTaxPayerById", namespace = "http://service.manousos.gr/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getTaxPayerById", namespace = "http://service.manousos.gr/")

public class GetTaxPayerById {

    @XmlElement(name = "arg0")
    private int arg0;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

}

