
package gr.manousos.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.0
 * Sun Jan 13 19:36:10 EET 2013
 * Generated source version: 2.7.0
 */

@XmlRootElement(name = "RegisterTaxPayerResponse", namespace = "http://service.manousos.gr/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegisterTaxPayerResponse", namespace = "http://service.manousos.gr/")

public class RegisterTaxPayerResponse {


}

