package gr.manousos.service;

import javax.jws.WebService;

import gr.manousos.model.Taxpayer;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-01-25T00:36:57.634+02:00
 * Generated source version: 2.7.0
 * 
 */

@WebService(name = "UserSrv", targetNamespace = "http://service.manousos.gr/")
public interface UserSrv {

	public String test(String msg);

	public void RegisterTaxPayer(Taxpayer user);

	public Taxpayer Register(Taxpayer user);

	
	public Taxpayer getTaxPayerById(int id);

}
